# Generated by Django 4.2.8 on 2023-12-11 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venueapi', '0002_rename_venue_image_url_venue_venue_inside_image_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='venue_outer_image_url',
            new_name='venue_outside_image_url',
        ),
    ]
