# Generated by Django 4.2.8 on 2023-12-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venueapi', '0003_rename_venue_outer_image_url_venue_venue_outside_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
